version: 1.0.{build}
os: Visual Studio 2015
platform: x64
configuration:
- Debug
- Release
matrix:
  fast_finish: true
before_build:
- ps: >-
    if ($env:CONFIGURATION -eq "Debug") {
        utils/CSTYLE.ps1
        if($LASTEXITCODE -ne 0) {
                exit 1
        }
        utils/CHECK_WHITESPACE.ps1
        if($LASTEXITCODE -ne 0) {
                exit 1
        }
        perl utils/sort_solution check
        if($LASTEXITCODE -ne 0) {
                exit 1
        }
    }
build:
  project: src/NVML.sln
  parallel: true
  verbosity: minimal
test_script:
- ps: >-
    if ($env:CONFIGURATION -eq "Debug") {
        cd src/test
        md /temp
        echo "`$env:NON_PMEM_FS_DIR = `"\temp`"" > testconfig.ps1
        echo "`$env:PMEM_FS_DIR = `"\temp`"" >> testconfig.ps1
        echo "`$env:PMEM_FS_DIR_FORCE_PMEM = `"1`"" >> testconfig.ps1
        echo "`$Env:TM = `"1`"" >> testconfig.ps1
        for ($i=0; $i -lt 50; $i++) {
            ./RUNTESTS.ps1 -b debug -o 3m -i vmem_multiple_pools
        }
    }
