version: 1.2.{build}
os: Visual Studio 2015
platform: x64

install:
- ps: Install-PackageProvider -Name NuGet -Force
- ps: Install-Module PsScriptAnalyzer -Force

configuration:
- Debug
- Release

environment:
    solutionname: NVML.sln
    setup: src\setup

matrix:
  fast_finish: true

before_build:
- ps: >-
    if ($Env:CONFIGURATION -eq "Debug") {
        utils/CSTYLE.ps1
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
        utils/CHECK_WHITESPACE.ps1
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
        utils/ps_analyze.ps1
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
        perl utils/sort_solution check
        if ($LASTEXITCODE -ne 0) {
                exit 1
        }
    } else {
        PowerShell -File "$Env:setup\SET_LIB.PS1" `
        -projectdir ((Get-Location).Path+"\$Env:setup")`
        -configuration $Env:CONFIGURATION
    }

build_script:
- cmd: >-
    msbuild src\%solutionname% /m /v:m

after_build:
- cmd: >-
    set DEVENV="%VS140COMNTOOLS%\..\IDE\devenv.com"

    %DEVENV% src\%solutionname% /build %CONFIGURATION% /project %setup%\setup.vdproj

- ps: >-
    PowerShell -File "$Env:setup\OUTPUT_MSI.PS1" `
    -projectdir ((Get-Location).Path+"\$Env:setup")`
    -configuration $Env:CONFIGURATION

- ps: >-
    utils/CREATE-ZIP.ps1 -b $Env:CONFIGURATION

test_script:
- ps: >-
    if ($Env:CONFIGURATION -eq "Debug") {
        cd src/test
        md /temp
        echo "`$Env:NON_PMEM_FS_DIR = `"\temp`"" > testconfig.ps1
        echo "`$Env:PMEM_FS_DIR = `"\temp`"" >> testconfig.ps1
        echo "`$Env:PMEM_FS_DIR_FORCE_PMEM = `"1`"" >> testconfig.ps1
        echo "`$Env:UNITTEST_NO_ABORT_MSG = `"1`"" >> testconfig.ps1
        echo "`$Env:TM = `"1`"" >> testconfig.ps1
        ./RUNTESTS.ps1 -b debug -o 4m
    }

artifacts:
- path: '%setup%\%configuration%\*.msi'
  name: NVML_msi

- path: 'src\x64\*.zip'
  name: NVML
